development:
  adapter: mysql2
  database: legal_database_development
  username: root
  password:
  host: localhost
  socket:  /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>